GET http://localhost:3002/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTdiNGZkZDZiODY2YjM5ODdiNDVjMzkiLCJuYW1lIjoicGVvcGxlMSIsImVtYWlsIjoicGVvcGxlMTJAZ21haWwuY29tIiwiaWF0IjoxNzAyNTgwMjI5LCJleHAiOjE3MDI1ODExMjl9.XjTjT5Ey_4S_iBp-33wF0W8uUd1K92iAqIjTZRkzqCo


###
POST http://localhost:3002/register
Content-Type: application/json

{
    "name": "people1",
    "email": "peop1234@gmail.com",
    "password": "178910890"
}

### 

POST http://localhost:3002/login
Content-Type: application/json

{
    "email": "asdf@gmail.com",
    "password": "asdfasdf"
}

###
GET http://localhost:3002/token

###
DELETE http://localhost:3002/logout

###
POST http://localhost:3002/savedNews
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTg1MmVmNjkwMDg5ZWE4NzBiZjBmNDciLCJuYW1lIjoiYXNkZiIsImVtYWlsIjoiYXNkZkBnbWFpbC5jb20iLCJpYXQiOjE3MDMyNTIwOTAsImV4cCI6MTcwMzI1Mjk5MH0.KTSSouzWHvUIrcervE0YyiuW7wfmY1c5VswC97HOBSE

{
  "thumbnail": "iwni adalahdatanya",
  "title": "iwni adalahdatanya",
  "description": "iwni adalahdatanya",
  "link": "iwni adalahdatanya",
  "pubDate": "iwni adalahdatanya"
}

###
GET http://localhost:3002/savedNews
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTg1MmVmNjkwMDg5ZWE4NzBiZjBmNDciLCJuYW1lIjoiYXNkZiIsImVtYWlsIjoiYXNkZkBnbWFpbC5jb20iLCJpYXQiOjE3MDMyNTIwOTAsImV4cCI6MTcwMzI1Mjk5MH0.KTSSouzWHvUIrcervE0YyiuW7wfmY1c5VswC97HOBSE