GET http://localhost:3002/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTczMmRlY2M3NDcxZTVmNjgyNzA1MzQiLCJuYW1lIjoicGVvcGxlMiIsImVtYWlsIjoicGVvcGxlMkBnbWFpbC5jb20iLCJpYXQiOjE3MDI0MDQ2MjYsImV4cCI6MTcwMjQwNDY2Nn0.7huNyGZq-fbzpM6QWIYWVCY4uydxy2Z40MEEVV-gt08


###
POST http://localhost:3002/register
Content-Type: application/json

{
    "name": "people3"
    "email": "people3@gmail.com",
    "password": "anything3"
}

###

POST http://localhost:3002/login
Content-Type: application/json

{
    "email": "people2@gmail.com",
    "password": "anything2"
}

###
GET http://localhost:3002/token

###
DELETE http://localhost:3002/logout