GET http://localhost:3002/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTc4YzllYmZkNDBlZDY3NTkyZmI0NTYiLCJuYW1lIjoicGVvcGxlNCIsImVtYWlsIjoicGVvcGxlNEBnbWFpbC5jb20iLCJpYXQiOjE3MDI0MTUzODMsImV4cCI6MTcwMjQxNjI4M30.fdXOvwK5eY65d8brjAfMzC6DKHsSTQbRMbOLaWtLBS8


###
POST http://localhost:3002/register
Content-Type: application/json

{
    "name": "people4",
    "email": "people4@gmail.com",
    "password": "anything4"
}

###

POST http://localhost:3002/login
Content-Type: application/json

{
    "email": "people4@gmail.com",
    "password": "anything4"
}

###
GET http://localhost:3002/token

###
DELETE http://localhost:3002/logout

###
POST http://localhost:3002/savedNews
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTc4YzllYmZkNDBlZDY3NTkyZmI0NTYiLCJuYW1lIjoicGVvcGxlNCIsImVtYWlsIjoicGVvcGxlNEBnbWFpbC5jb20iLCJpYXQiOjE3MDI0MTUzODMsImV4cCI6MTcwMjQxNjI4M30.fdXOvwK5eY65d8brjAfMzC6DKHsSTQbRMbOLaWtLBS8

{
  "thumbnail": "iwni adalahdatanya",
  "title": "iwni adalahdatanya",
  "description": "iwni adalahdatanya",
  "link": "iwni adalahdatanya",
  "pubDate": "iwni adalahdatanya"
}

###
GET http://localhost:3002/savedNews
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTc4YzllYmZkNDBlZDY3NTkyZmI0NTYiLCJuYW1lIjoicGVvcGxlNCIsImVtYWlsIjoicGVvcGxlNEBnbWFpbC5jb20iLCJpYXQiOjE3MDI0MTUzODMsImV4cCI6MTcwMjQxNjI4M30.fdXOvwK5eY65d8brjAfMzC6DKHsSTQbRMbOLaWtLBS8